apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '100m' # 100 milicores de CPU
              memory: '128Mi' # 128 MiB de memoria
            limits:
              cpu: '500m' # 500 milicores de CPU
              memory: '512Mi' # 512 MiB de memoria
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-reverse-proxy-config
            items:
              - key: nginx.conf
                path: nginx.conf
